# Numpy의 소개
NumPy(Numerical Python)는 파이썬에서 과학적 계산을 위한 핵심 라이브러리이다. NumPy는 다차원 배열 객체와 배열과 함께 작동하는 도구들을 제공한다. 하지만 NumPy 자체로는 고수준의 데이터 분석 기능을 제공하지 않기 때문에 NumPy 배열과 배열 기반 컴퓨팅의 이해를 통해 pandas와 같은 도구를 좀 더 효율적으로 사용하는 것이 필요하다.

## nd array 생성
array 함수를 사용하여 배열생성하기

In [1]:
import numpy as np #numpy를 줄여서 np로 부를게(aliance)

In [2]:
# ndarray 생성
arr=np.array([1,2,3,4])#파이썬에서  li 데이터타입

In [3]:
print(arr)

[1 2 3 4]


위 결과를 봐서는 배열인지 리스트인지 알수 없으니 프린트 된 요소가 궁금하면 타입을 써보면 됨

In [4]:
type(arr)

numpy.ndarray

np.zeros((3,3)) =메모리를 0으로 만드는 초기화 작업<p>
예) 원룸입주시 이전 거주자가 집을 비워서 나가는것<p> 데이터 처리에 할당된 메모리가 이미 이전에 누군가가 썼던 메모리(공간)의 데이터들을 비워내고 내 데이터를 넣어 처리하기 위한 선행작업
(이 작업을 무시하면 내 데이터가 이전 데이터때문에 결과값에 영향미침)<p>
    필요에 따라 0 이아닌 1로 초기화 해야하면 np.ones((3,3))형식으로 씀   <p>
* 숫자 뒤 . 의 의미= [정수]임을 표시
      

* 0과 null의 차이<p>
0=계산가능<p>
null=계산불가

In [5]:
np.zeros((3,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.empty((4,4)) #아무런 정수값없이 배열만 필요할때 씀. 괄호안에 값이 이전에 사용된 데이터

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061074e-306],
       [7.56587585e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306],
       [2.22522597e-306, 1.24611674e-306, 1.29061821e-306,
        6.23057349e-307]])

In [8]:
np.arange(10) #명령어 어렌지=범위표현  출력값[0,1,2,3,4,5,6,7,8,9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### ndarray 배열의 모양, 차수, 데이터 타입 확인하기

In [10]:
arr = np.array([[1,2,3],[4,5,6]]) 

In [11]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
arr.shape

(2, 3)

(2, 3)의 해석= 2개의 열, 각 열당 3개의 값 배열 따라서 이 배열은 2차원

In [13]:
arr.ndim #이 배열은 몇차원ndim인가요?

2

In [14]:
arr.dtype #이배열의 데이터타입은?

dtype('int32')

=32bit환경에서 실행된 데이터이다

In [15]:
arr_float=arr.astype(np.float64) #astype=형태를 바꾸다 ()

In [16]:
print(arr_float)

[[1. 2. 3.]
 [4. 5. 6.]]


In [17]:
arr_float.dtype #float64=정수타입->실수타입으로 바꾼것. 

dtype('float64')

수 데이터타입 numpy 1-5  파일 참조

In [21]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

#arr3=arr1+arr2
arr3=np.add(arr1,arr2) # 위 행 수식과 같은 값도출

#사칙연산 모두 가능
#arr3=arr1*arr2
#arr3=np.multiply(arr1,arr2)
print(arr3)

[[ 6  8]
 [10 12]]


Numpy 배열의 연산은 연산자 (+,-,*,/)나 함수(add, subtract, multiply, divide)로 가능하다.

### ★★★★★ndarray 배열 슬라이싱 하기 

ndarray 배열 슬라이싱 하기
슬라이싱=전체배열에서 내가 원하는 만큼만 잘라서 불러오는 것

In [24]:
#배열슬라이싱
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
arr_1=arr[:2,1:3]  #[:2,=행 시작부터 2까지 가져옴 1:3=열 행에서 1~3이전까지의 수를 가져옴 ]
print(arr_1)

[[2 3]
 [5 6]]


In [26]:
arr.shape

(3, 3)

In [28]:
arr_int=np.arange(10) #기본배열
print(arr_int)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
arr_int=np.arange(10) #슬라이싱 1
print(arr_int[:5])

[0 1 2 3 4]


In [30]:
arr_int=np.arange(10) #슬라이싱 2
print(arr_int[5:])

[5 6 7 8 9]


In [31]:
arr_int=np.arange(10)#슬라이싱 3
print(arr_int[0:8])

[0 1 2 3 4 5 6 7]


In [32]:
arr_int=np.arange(10)#슬라이싱 4
print(arr_int[0:8:2]) #[스타팅포인트:엔드포인트:스텝(증가단위)]

[0 2 4 6]


In [34]:
print(arr[0,2]) #[0=행,2=지정행의 2번째 자리 데이터])

3


In [37]:
arr=np.array([[1,2,3],[4,5,6]]) #새로운 배열정립

In [39]:
idx=arr>3 #배열에서 3보다 큰것을 idx로 담아라
print(idx)

[[False False False]
 [ True  True  True]]


In [40]:
print(arr[idx])

[4 5 6]


# Wine Quality

In [42]:
redwine=np.loadtxt(fname='samples/winequality-red.csv',delimiter=';',skiprows=1) 
#loadtxt=넘파이이로 로드한다 . fname=파일명   . 항목간 구별은 ;로 한다. 원본데이터의 첫째줄은 건너띈다


In [43]:
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [44]:
redwine.shape #새로운데이터 생성시 모양확인하는 습관들이는게 좋음

(1599, 12)

해석 =( 전체데이터=1599, 컬럼 개수=12) 

In [45]:
type(redwine)

numpy.ndarray

In [46]:
print(redwine.sum()) #전체합계

152084.78194


In [47]:
print(redwine.mean())  #전체평균

7.926036165311652


In [48]:
print(redwine.mean(axis=0)) # 데이터의 기준 축순서 가로=1 세로는 1. 따라서 가로(열=컬럼)들의 평균을 묻는 명령어

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [50]:
print(redwine[:,0].mean()) # [: = 전체데이터 선택,0=이중의 세로축 첫번째컬럼].mean() 평균

8.31963727329581


위의 코드에서 연산자명령어만 바꾸면 그대로 연산실행
numpy 끝-